FROM ubuntu:18.04
RUN apt-get -y update
RUN apt-get -y install build-essential cmake wget
ADD . /development
WORKDIR /development
RUN cd /development &&\
    ls &&\
    mkdir build &&\
    cd build && \
    cmake .. && \
    make
RUN make test
