FROM ubuntu:18.04
MAINTAINER Christian Berger "christian.berger@gu.se"

ENV DEBIAN_FRONTEND noninteractive

# Upgrade the Ubuntu 18.04 LTS base image
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get dist-upgrade -y

# Install the development libraries for OpenCV
RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    cmake \
    build-essential \
    libopencv-dev \
    libopencv-core3.2 \
    libopencv-highgui3.2 \
    libopencv-imgproc3.2 \
    libopencv-features2d3.2
# Include this source tree and compile the sources
ADD . /opt/sources
WORKDIR /opt/sources

RUN mkdir build && \
    cd build && \
    cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/tmp .. && \
    make && make install
ENTRYPOINT [ "tail","-f","/dev/null" ]
