FROM ubuntu:18.04
RUN apt-get -y update
RUN apt-get -y install build-essential cmake wget
WORKDIR /development
COPY /src /development/
RUN mkdir build
RUN cd build
RUN cmake ..
RUN make 
RUN make test

# RUN ./helloworld
